module.exports = {
    products: [
        {
            _id: '111111111111111111111111',
            name: 'Green Dress Midi',
            category: 'dress',
            image: '/images/product_1.jpg',
            price: 150,
            brand: 'House of CB',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '222222222222222222222222',
            name: 'Skirt Floral Print Midi',
            category: 'skirt',
            image: '/images/product_2.jpg',
            price: 90,
            brand: 'Stradivarius',
            rating: 2.6,
            numReviews: 10,
            countInStock: 3,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '333333333333333333333333',
            name: 'Jeans Regular Blue',
            category: 'pant',
            image: '/images/product_3.jpg',
            price: 100,
            brand: 'Stradivarius',
            rating: 3.3,
            numReviews: 15,
            countInStock: 0,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '444444444444444444444444',
            name: 'White Dress Midi',
            category: 'dress',
            image: '/images/product_4.jpg',
            price: 135,
            brand: 'House of CB',
            rating: 4.2,
            numReviews: 11,
            countInStock: 0,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '555555555555555555555555',
            name: 'Grey Mom Jeans',
            category: 'pant',
            image: '/images/product_5.jpg',
            price: 80,
            brand: 'Reserved',
            rating: 4.4,
            numReviews: 7,
            countInStock: 8,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '666666666666666666666666',
            name: 'Black Skirt Short',
            category: 'skirt',
            image: '/images/product_6.jpg',
            price: 90,
            brand: 'Stradivarius',
            rating: 3.6,
            numReviews: 7,
            countInStock: 0,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '777777777777777777777777',
            name: 'T-Short Brown White Print',
            category: 'tshort',
            image: '/images/product_7.jpg',
            price: 69,
            brand: 'H&M',
            rating: 3.9,
            numReviews: 7,
            countInStock: 3,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '888888888888888888888888',
            name: 'T-Short Black',
            category: 'tshort',
            image: '/images/product_8.jpg',
            price: 74,
            brand: 'Stradivarius',
            rating: 4.6,
            numReviews: 7,
            countInStock: 6,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '999999999999999999999999',
            name: 'Black Dress Mini',
            category: 'dress',
            image: '/images/product_9.jpg',
            price: 155,
            brand: 'Zara',
            rating: 4.9,
            numReviews: 7,
            countInStock: 75,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '101010101010101010101010',
            name: 'T-Short Beige Lines Cropped',
            category: 'tshort',
            image: '/images/product_10.jpg',
            price: 50,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 50,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '121212121212121212121212',
            name: 'Green Huddy',
            category: 'huddy',
            image: '/images/product_11.jpg',
            price: 150,
            brand: 'Reserved',
            rating: 5,
            numReviews: 7,
            countInStock: 2,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '131313131313131313131313',
            name: 'Black Pants',
            category: 'pant',
            image: '/images/product_12.jpg',
            price: 125,
            brand: 'Reserved',
            rating: 4.5,
            numReviews: 7,
            countInStock: 19,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '141414141414141414141414',
            name: 'T-Shirt Brown Image Print',
            category: 'tshirt',
            image: '/images/product_13.jpg',
            price: 99,
            brand: 'Stradivarius',
            rating: 4.1,
            numReviews: 7,
            countInStock: 101,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '151515151515151515151515',
            name: 'Black Huddy',
            category: 'huddy',
            image: '/images/product_14.jpg',
            price: 56,
            brand: 'Reserved',
            rating: 4.6,
            numReviews: 7,
            countInStock: 120,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '161616161616161616161616',
            name: 'Short Skirt Beige',
            category: 'skirt',
            image: '/images/product_15.jpg',
            price: 200,
            brand: 'Zara',
            rating: 2.3,
            numReviews: 7,
            countInStock: 75,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '171717171717171717171717',
            name: 'Green T-Shirt Cropped',
            category: 'tshirt',
            image: '/images/product_16.jpg',
            price: 75,
            brand: 'Stradivarius',
            rating: 3.4,
            numReviews: 7,
            countInStock: 83,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '181818181818181818181818',
            name: 'White Floral Dress',
            category: 'dress',
            image: '/images/product_17.jpg',
            price: 89,
            brand: 'House of CB',
            rating: 4.3,
            numReviews: 7,
            countInStock: 16,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '191919191919191919191919',
            name: 'Black T-Shirt',
            category: 'tshirt',
            image: '/images/product_18.jpg',
            price: 40,
            brand: 'H&M',
            rating: 3.9,
            numReviews: 7,
            countInStock: 10,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '202020202020202020202020',
            name: 'Black Jeans Skinny',
            category: 'pant',
            image: '/images/product_19.jpg',
            price: 130,
            brand: 'Reserved',
            rating: 2.5,
            numReviews: 7,
            countInStock: 54,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '212121212121212121212121',
            name: 'White huddy',
            category: 'huddy',
            image: '/images/product_20.jpg',
            price: 30,
            brand: 'H&M',
            rating: 2.7,
            numReviews: 7,
            countInStock: 73,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '232323232323232323232323',
            name: 'White Jeans Skinny',
            category: 'pant',
            image: '/images/product_21.jpg',
            price: 45,
            brand: 'Zara',
            rating: 4.1,
            numReviews: 7,
            countInStock: 48,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '242424242424242424242424',
            name: 'Black Skirt Maxi',
            category: 'skirt',
            image: '/images/product_22.jpg',
            price: 66,
            brand: 'Stradivarius',
            rating: 3.6,
            numReviews: 7,
            countInStock: 58,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
        {
            _id: '252525252525252525252525',
            name: 'Beige White Pants',
            category: 'pant',
            image: '/images/product_23.jpg',
            price: 84,
            brand: 'Reserved',
            rating: 3.1,
            numReviews: 7,
            countInStock: 20,
            sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
        },
    ],
};